# -*- coding: utf-8 -*-
"""真实学习资源清单（方案 A）

用途：替换 resource 表的文案层（title/type/difficulty/description/url），
      resource_id 保持不变，因此评分矩阵、收藏、行为日志与离线指标零影响。

字段：(标题, 类型, 难度1-5, 链接, 简介)
链接策略：能定位到具体页面的用具体页面（官方文档 / 教程 / 题库）；
      课程类资源定位不到唯一官方页时，使用平台站内搜索链接（关键词取自标题），
      避免"标题是某门课、链接却是平台首页"的不匹配。
数量与现有分类分布严格一致：软件工程28 机器学习27 数据库33 计算机网络27 算法26 Web开发34 人工智能29 = 204
"""

RESOURCES = {

    "软件工程": [
        ('软件工程（北京大学）国家精品公开课', 'video', 3, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B',
         '从软件过程模型讲到需求分析、设计、测试与维护，配合案例讲解，适合课程同步学习。'),
        ('《软件工程导论》课堂配套课件', 'ppt', 3, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B%E5%AF%BC%E8%AE%BA',
         '覆盖软件生命周期各阶段核心知识点，图示丰富，适合期末复习时快速梳理知识框架。'),
        ('UML 建模实战教程', 'doc', 3, 'https://www.uml-diagrams.org/',
         '用例图、类图、时序图等九种图的标准画法与语义讲解，附校园项目建模示例。'),
        ('敏捷开发与 Scrum 实践', 'video', 3, 'https://search.bilibili.com/all?keyword=%E6%95%8F%E6%8D%B7%E5%BC%80%E5%8F%91',
         '讲解迭代计划、每日站会、燃尽图等敏捷实践，适合课程设计团队协作参考。'),
        ('需求分析文档模板与范例集', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E9%9C%80%E6%B1%82%E5%88%86%E6%9E%90',
         '提供需求规格说明书的通用模板与三份完整范例，可直接套用于课程设计。'),
        ('软件测试方法专项题库（黑白盒）', 'question', 3, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E6%B5%8B%E8%AF%95',
         '涵盖等价类划分、边界值分析、判定覆盖与 McCabe 复杂度计算，附详细解析。'),
        ('Git 版本控制入门与团队协作实战', 'video', 2, 'https://git-scm.com/book/zh/v2',
         '从分支模型到冲突解决、Pull Request 流程，配合真实团队协作场景演示。'),
        ('设计模式（GoF 23 种）详解', 'doc', 4, 'https://refactoringguru.cn/design-patterns',
         '每种模式配结构图、适用场景与可运行示例，重点讲解单例、工厂与观察者模式。'),
        ('软件项目管理与进度计划实验课件', 'ppt', 3, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86',
         '包含 WBS 分解、甘特图与关键路径法教学示例，适合项目管理章节配套实验。'),
        ('软件工程期末复习题库（含答案解析）', 'question', 2, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B',
         '按章节组织的高频考题，覆盖过程模型对比、内聚耦合判定等经典题型。'),
        ('单元测试与 JUnit 实践指南', 'doc', 3, 'https://junit.org/',
         '讲解断言、测试夹具、参数化测试与覆盖率统计，附 Java 示例工程。'),
        ('代码重构技巧与实例解析', 'video', 4, 'https://search.bilibili.com/all?keyword=%E4%BB%A3%E7%A0%81%E9%87%8D%E6%9E%84',
         '以真实代码库演示提取方法、消除重复、替换条件逻辑等常用重构手法。'),
        ('软件需求工程：从获取到验证', 'video', 4, 'https://search.bilibili.com/all?keyword=%E8%BD%AF%E4%BB%B6%E9%9C%80%E6%B1%82%E5%B7%A5%E7%A8%8B',
         '系统讲解访谈、原型、场景分析等需求获取方法及需求优先级管理。'),
        ('持续集成与 CI/CD 实践指导', 'doc', 4, 'https://docs.github.com/',
         '以 GitHub Actions 为例搭建自动构建、测试与部署流水线，附配置文件说明。'),
        ('软件质量保证与度量课件', 'ppt', 4, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E8%B4%A8%E9%87%8F%E4%BF%9D%E8%AF%81',
         '介绍缺陷密度、圈复杂度、平均无故障时间等质量度量指标及其实践应用。'),
        ('软件工程课程设计任务书（含评分标准）', 'question', 3, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B',
         '给出选题范围、阶段交付物与答辩评分细则，可直接作为课程设计参考。'),
        ('DevOps 文化与工具链入门', 'doc', 3, 'https://search.bilibili.com/all?keyword=DevOps',
         '梳理开发运维一体化的理念、常用工具链与团队落地路径。'),
        ('人机交互与界面设计讲义', 'doc', 3, 'https://www.icourse163.org/search.htm?search=%E4%BA%BA%E6%9C%BA%E4%BA%A4%E4%BA%92',
         '涵盖可用性原则、交互设计流程与界面原型评估方法，附案例分析。'),
        ('软件架构设计模式与演进', 'video', 5, 'https://search.bilibili.com/all?keyword=%E8%BD%AF%E4%BB%B6%E6%9E%B6%E6%9E%84',
         '从分层架构讲到微服务与事件驱动，分析各架构风格的权衡取舍。'),
        ('软件过程模型对比分析课件', 'ppt', 2, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B',
         '对比瀑布、原型、螺旋、敏捷等过程模型的适用场景与优缺点。'),
        ('缺陷管理与 Bug 跟踪实践', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E6%B5%8B%E8%AF%95',
         '讲解缺陷生命周期、优先级判定与 Bug 报告规范，附跟踪工具使用说明。'),
        ('软件工程专业认证习题集', 'question', 5, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B',
         '综合性强的大题集，覆盖计算题、设计题与论述题三类题型。'),
        ('团队协作与代码评审规范', 'doc', 3, 'https://docs.github.com/',
         '给出分支策略、提交信息规范与 Code Review 检查清单。'),
        ('软件工程文献综述写作指导', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B',
         '讲解文献检索、筛选与综述结构组织方法，适合学年论文阶段参考。'),
        ('领域驱动设计（DDD）入门', 'video', 5, 'https://search.bilibili.com/all?keyword=%E9%A2%86%E5%9F%9F%E9%A9%B1%E5%8A%A8%E8%AE%BE%E8%AE%A1',
         '讲解限界上下文、聚合根与领域事件，结合电商案例说明建模过程。'),
        ('软件工程毕业设计选题与实施指南', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B',
         '梳理选题原则、开题报告结构与常见问题，附优秀选题清单。'),
        ('软件维护与演化讲义', 'doc', 4, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E7%BB%B4%E6%8A%A4',
         '介绍四类维护活动、遗留系统改造策略与重构时机的判断方法。'),
        ('软件工程综合练习题集', 'question', 3, 'https://www.icourse163.org/search.htm?search=%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B',
         '覆盖全书的综合练习，含概念辨析、图示绘制与案例分析三类题型。'),
    ],
    "机器学习": [
        ('机器学习（吴恩达）公开课', 'video', 2, 'https://www.coursera.org/learn/machine-learning',
         '经典的机器学习入门课程，从线性回归讲到支持向量机与推荐系统，配套编程作业。'),
        ('周志华《机器学习》精读笔记', 'doc', 3, 'https://www.icourse163.org/search.htm?search=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0',
         '按章节梳理假设空间、模型评估与选择、支持向量机与集成学习等重点内容。'),
        ('李航《统计学习方法》配套讲义', 'ppt', 4, 'https://www.icourse163.org/search.htm?search=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0',
         '系统讲解感知机、k 近邻、EM 算法与条件随机场等统计学习方法的推导过程。'),
        ('斯坦福 CS229 机器学习完整课程', 'video', 5, 'https://search.bilibili.com/all?keyword=CS229',
         '面向研究生水平的机器学习课程，含数学推导、生成学习与强化学习内容。'),
        ('PyTorch 官方教程：60 分钟快速入门', 'video', 2, 'https://pytorch.org/tutorials/',
         '手把手搭建张量运算与小型神经网络，适合作为深度学习的第一个上手练习。'),
        ('scikit-learn 官方用户指南', 'doc', 3, 'https://scikit-learn.org/stable/user_guide.html',
         '覆盖分类、回归、聚类与模型选择全流程的 API 说明，附代码示例。'),
        ('李宏毅《机器学习》课程课件', 'ppt', 3, 'https://speech.ee.ntu.edu.tw/',
         '以通俗比喻讲解回归、CNN、RNN 与注意力机制，配套作业说明。'),
        ('Kaggle 入门实战：Titanic 与房价预测', 'question', 4, 'https://www.kaggle.com/search?q=titanic',
         '两个经典入门竞赛及完整解题思路，覆盖数据清洗、特征工程与模型评估全流程。'),
        ('机器学习期末复习题库', 'question', 3, 'https://www.icourse163.org/search.htm?search=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0',
         '覆盖偏差方差分解、正则化、SVM 对偶形式与聚类评价指标等高频考点。'),
        ('Google 机器学习速成课程', 'video', 2, 'https://developers.google.cn/machine-learning/crash-course',
         '交互式课程，含可视化练习与真实数据集实验，适合零基础快速建立直觉（国内可直连）。'),
        ('动手学深度学习（中文版）', 'doc', 3, 'https://zh.d2l.ai/',
         '开源教材，理论与代码并重，覆盖从线性回归到预训练模型的完整脉络。'),
        ('特征工程实战笔记', 'doc', 4, 'https://www.kaggle.com/search?q=feature%20engineering',
         '汇总缺失值处理、类别编码、特征交叉等竞赛常用技巧与踩坑经验。'),
        ('决策树与随机森林专题讲解', 'video', 3, 'https://search.bilibili.com/all?keyword=%E5%86%B3%E7%AD%96%E6%A0%91%20%E9%9A%8F%E6%9C%BA%E6%A3%AE%E6%9E%97',
         '从信息增益讲到剪枝与袋外估计，配合可视化演示节点分裂过程。'),
        ('XGBoost 官方文档与调参指南', 'doc', 4, 'https://xgboost.readthedocs.io/',
         '介绍梯度提升原理、参数含义与调参策略，附竞赛级实践建议。'),
        ('模型评估与交叉验证实验课件', 'ppt', 3, 'https://scikit-learn.org/stable/modules/cross_validation.html',
         '讲解留出法、k 折交叉验证、分层抽样与各类评估指标的适用场景。'),
        ('机器学习高频面试问答题集', 'question', 4, 'https://search.bilibili.com/all?keyword=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%20%E9%9D%A2%E8%AF%95',
         '按主题整理的面试题与参考回答，覆盖原理题、工程题与场景题。'),
        ('聚类算法实战：K-Means 与 DBSCAN', 'video', 3, 'https://search.bilibili.com/all?keyword=%E8%81%9A%E7%B1%BB%E7%AE%97%E6%B3%95',
         '演示两种聚类算法的实现过程、参数选择与结果评估方法。'),
        ('机器学习数学基础讲义', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0',
         '梳理线性代数、概率论与凸优化中机器学习常用的数学工具。'),
        ('梯度下降与优化算法原理课件', 'ppt', 3, 'https://www.icourse163.org/search.htm?search=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0',
         '对比批量、随机与小批量梯度下降及动量、Adam 等改进方法的收敛特性。'),
        ('Weka 数据挖掘实验指导', 'doc', 2, 'https://www.cs.waikato.ac.nz/ml/weka/',
         '面向零代码入门的实验手册，用图形界面完成分类与聚类实验。'),
        ('集成学习专题：Bagging 与 Boosting', 'video', 4, 'https://search.bilibili.com/all?keyword=%E9%9B%86%E6%88%90%E5%AD%A6%E4%B9%A0',
         '从偏差方差分解视角讲解集成思想及各代表性算法的对比。'),
        ('机器学习课程设计题集（含数据集说明）', 'question', 4, 'https://www.icourse163.org/search.htm?search=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0',
         '提供六个课程设计题目、数据来源建议与验收标准。'),
        ('深度学习框架对比与选型笔记', 'doc', 3, 'https://pytorch.org/tutorials/',
         '对比主流框架的计算图模式、生态与部署能力，给出选型决策建议。'),
        ('天池大数据竞赛入门教程', 'doc', 3, 'https://tianchi.aliyun.com/search?keyword=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0',
         '介绍赛题理解、基线搭建与提分思路，适合首次参加数据竞赛。'),
        ('机器学习白板推导系列', 'video', 5, 'https://search.bilibili.com/all?keyword=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%20%E7%99%BD%E6%9D%BF%E6%8E%A8%E5%AF%BC',
         '用数学推导完整重建经典算法脉络，适合希望深入原理的同学。'),
        ('电影评分预测实验指导书', 'question', 4, 'https://www.icourse163.org/search.htm?search=%E6%8E%A8%E8%8D%90%E7%B3%BB%E7%BB%9F',
         '以 MovieLens 数据为基础的推荐实验，含评价指标与报告要求。'),
        ('模型调参与过拟合防治笔记', 'doc', 4, 'https://scikit-learn.org/stable/modules/learning_curve.html',
         '汇总学习曲线诊断、正则化与早停策略的实践经验。'),
    ],
    "数据库": [
        ('《数据库系统概论》配套课件', 'ppt', 3, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93%E7%B3%BB%E7%BB%9F%E6%A6%82%E8%AE%BA',
         '教材章节课件，覆盖关系模型、SQL 语言、范式理论与并发控制。'),
        ('MySQL 官方参考手册', 'doc', 3, 'https://dev.mysql.com/doc/',
         '权威的语法与配置参考，包含 SQL 语句、存储引擎与优化器说明。'),
        ('SQL 基础教程', 'doc', 2, 'https://www.runoob.com/sql/sql-tutorial.html',
         '从 SELECT 到多表连接、子查询的渐进式教程，附在线练习环境。'),
        ('数据库系统原理（哈工大）公开课', 'video', 3, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93%E7%B3%BB%E7%BB%9F',
         '系统讲解数据库设计与实现原理，含完整的实验环节。'),
        ('索引原理与查询优化实战', 'video', 4, 'https://search.bilibili.com/all?keyword=MySQL%20%E7%B4%A2%E5%BC%95',
         '结合执行计划分析 B+ 树索引的使用场景与失效原因。'),
        ('SQL 实战练习题集', 'question', 3, 'https://leetcode.cn/problemset/?search=%E6%95%B0%E6%8D%AE%E5%BA%93',
         '覆盖基础查询、聚合统计、窗口函数等题型，由易到难分层训练。'),
        ('事务与并发控制讲义', 'doc', 4, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93',
         '讲解 ACID 特性、隔离级别、两阶段锁与 MVCC 实现原理。'),
        ('Redis 官方文档与入门指南', 'doc', 3, 'https://redis.io/docs/',
         '介绍五种基本数据结构、持久化机制与缓存设计常见模式。'),
        ('数据库设计与范式理论课件', 'ppt', 2, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93%E8%AE%BE%E8%AE%A1',
         '讲解 E-R 建模到关系模式转换及 1NF 至 3NF 的判定方法。'),
        ('MySQL 性能调优实战', 'video', 4, 'https://search.bilibili.com/all?keyword=MySQL%20%E8%B0%83%E4%BC%98',
         '演示慢查询定位、索引优化与关键配置参数调整的完整流程。'),
        ('E-R 图设计案例集', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93%E8%AE%BE%E8%AE%A1',
         '收录校园、电商、图书管理等场景的完整概念设计案例。'),
        ('数据库课程设计题库', 'question', 4, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93',
         '提供选题、需求描述与功能要求，可直接作为课程设计题目使用。'),
        ('SQLite 官方文档', 'doc', 2, 'https://www.sqlite.org/docs.html',
         '轻量嵌入式数据库的完整参考，适合本地原型项目与教学演示。'),
        ('分布式数据库原理与架构', 'video', 5, 'https://search.bilibili.com/all?keyword=%E5%88%86%E5%B8%83%E5%BC%8F%E6%95%B0%E6%8D%AE%E5%BA%93',
         '讲解数据分片、副本一致性、CAP 权衡与分布式事务方案。'),
        ('存储过程与触发器实验指导', 'doc', 3, 'https://dev.mysql.com/doc/',
         '通过实例讲解存储过程、自定义函数与触发器的编写与调试。'),
        ('数据库期末复习题库', 'question', 2, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93',
         '覆盖关系代数、SQL 书写、范式分解与并发调度的计算题。'),
        ('MongoDB 官方入门教程', 'doc', 3, 'https://www.mongodb.com/docs/manual/tutorial/',
         '文档型数据库的增删改查、聚合管道与数据建模实践。'),
        ('数据库备份与恢复实践课件', 'ppt', 3, 'https://dev.mysql.com/doc/',
         '讲解逻辑备份、物理备份与主从复制的配置要点。'),
        ('关系代数与 SQL 转换专题', 'video', 3, 'https://search.bilibili.com/all?keyword=%E5%85%B3%E7%B3%BB%E4%BB%A3%E6%95%B0',
         '演示如何将关系代数表达式等价转换为 SQL 语句并验证结果。'),
        ('数据仓库与数据挖掘实验讲义', 'doc', 4, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E4%BB%93%E5%BA%93',
         '介绍星型模型设计、ETL 流程与 OLAP 分析的基本实验步骤。'),
        ('PostgreSQL 官方文档', 'doc', 3, 'https://www.postgresql.org/docs/',
         '功能完整的关系数据库参考手册，含高级查询与扩展机制说明。'),
        ('数据库锁机制详解', 'video', 4, 'https://search.bilibili.com/all?keyword=%E6%95%B0%E6%8D%AE%E5%BA%93%20%E9%94%81',
         '区分表锁、行锁、间隙锁的加锁范围及死锁检测与排查方法。'),
        ('SQLAlchemy 使用笔记', 'doc', 3, 'https://docs.sqlalchemy.org/',
         '讲解 ORM 映射、会话管理与查询构造在项目中的落地方式。'),
        ('HBase 入门课件', 'ppt', 4, 'https://hbase.apache.org/',
         '介绍列式存储模型、RowKey 设计原则与读写流程。'),
        ('数据库安全与 SQL 注入防护', 'doc', 4, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93%E5%AE%89%E5%85%A8',
         '讲解注入攻击原理、参数化查询与最小权限原则的落地。'),
        ('数据库系统实现（实验配套）', 'doc', 5, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93',
         '涉及存储管理、查询执行与事务实现等进阶实验内容。'),
        ('MySQL 索引优化案例题集', 'question', 4, 'https://leetcode.cn/problemset/?search=%E6%95%B0%E6%8D%AE%E5%BA%93',
         '结合典型慢查询场景训练索引设计与 SQL 改写能力。'),
        ('数据建模工具使用指南', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93%E8%AE%BE%E8%AE%A1',
         '讲解常用建模工具绘制 E-R 图与生成建表语句的操作流程。'),
        ('分库分表与读写分离实践', 'video', 5, 'https://search.bilibili.com/all?keyword=%E5%88%86%E5%BA%93%E5%88%86%E8%A1%A8',
         '讲解水平拆分策略、路由算法与中间件方案的工程权衡。'),
        ('数据库原理在线自测题库', 'question', 2, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93%E5%8E%9F%E7%90%86',
         '按知识点组织的自测题，适合考前快速查漏补缺。'),
        ('云数据库使用教程', 'doc', 2, 'https://help.aliyun.com/',
         '介绍云上数据库实例的创建、连接、备份与监控操作流程。'),
        ('数据库运维监控实践课件', 'ppt', 4, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%90%E7%BB%B4',
         '讲解关键性能指标采集、告警配置与容量规划方法。'),
        ('数据库课程实验报告范例', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E5%BA%93',
         '提供实验目的、步骤、结果分析与总结的规范写法示例。'),
    ],
    "计算机网络": [
        ('计算机网络（哈工大）公开课', 'video', 3, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '按五层模型系统讲解，配套抓包实验，适合课程同步学习。'),
        ('《计算机网络：自顶向下方法》配套课件', 'ppt', 4, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '从应用层切入自顶向下讲解协议栈，图示丰富便于理解。'),
        ('TCP/IP 协议详解系列', 'video', 3, 'https://search.bilibili.com/all?keyword=TCP/IP',
         '逐层拆解报文结构与协议行为，配合抓包实操演示。'),
        ('Wireshark 抓包分析实验指导', 'doc', 3, 'https://www.wireshark.org/',
         '讲解过滤器语法与常见协议分析流程，附实验用数据包。'),
        ('HTTP 权威指南学习笔记', 'doc', 3, 'https://developer.mozilla.org/zh-CN/docs/Web/HTTP',
         '梳理请求方法、状态码、缓存机制与连接管理要点。'),
        ('网络分层模型与协议栈讲义', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '对比 OSI 与 TCP/IP 模型及各层典型协议的职责划分。'),
        ('计算机网络期末题库', 'question', 2, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '覆盖选择、计算与简答题型，附详细答案解析。'),
        ('子网划分与路由计算专项练习', 'question', 3, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '大量 IP 地址划分、子网掩码计算与路由聚合练习题。'),
        ('Socket 编程实战教程', 'doc', 4, 'https://beej.us/guide/bgnet/',
         '从 TCP/UDP 套接字到并发服务器实现的完整编程教程。'),
        ('三次握手与四次挥手动画讲解', 'video', 2, 'https://search.bilibili.com/all?keyword=%E4%B8%89%E6%AC%A1%E6%8F%A1%E6%89%8B',
         '用动画演示连接建立与释放过程中的状态迁移。'),
        ('网络安全基础：TLS 与 HTTPS 原理', 'video', 4, 'https://search.bilibili.com/all?keyword=HTTPS%20%E5%8E%9F%E7%90%86',
         '讲解对称加密、证书链验证与握手流程，配合抓包分析。'),
        ('网络排障命令工具箱', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '汇总 ping、traceroute、netstat 等命令的使用场景与结果解读。'),
        ('DNS 原理与配置实验课件', 'ppt', 3, 'https://www.icourse163.org/search.htm?search=DNS',
         '讲解域名解析过程、资源记录类型与本地 DNS 配置实验。'),
        ('局域网组网与交换机配置指导', 'doc', 3, 'https://www.cisco.com/',
         '介绍 VLAN 划分、端口配置与常见组网拓扑搭建。'),
        ('网络协议抓包分析案例集', 'question', 4, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '给出真实抓包数据与待答问题，训练协议分析能力。'),
        ('CDN 与负载均衡原理', 'video', 4, 'https://search.bilibili.com/all?keyword=CDN%20%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1',
         '讲解内容分发网络、调度策略与四七层负载均衡实现。'),
        ('HTTP/2 与 HTTP/3 新特性解读', 'doc', 4, 'https://developer.mozilla.org/zh-CN/docs/Web/HTTP',
         '对比多路复用、头部压缩与基于 QUIC 的传输改进。'),
        ('网络编程课程设计任务书', 'question', 4, 'https://www.icourse163.org/search.htm?search=%E7%BD%91%E7%BB%9C%E7%BC%96%E7%A8%8B',
         '提供聊天室、文件传输等选题及验收标准。'),
        ('无线网络与移动通信讲义', 'doc', 3, 'https://www.icourse163.org/search.htm?search=%E6%97%A0%E7%BA%BF%E7%BD%91%E7%BB%9C',
         '介绍无线信道特性、802.11 协议与移动性管理机制。'),
        ('网络性能测试与优化实践', 'video', 4, 'https://search.bilibili.com/all?keyword=%E7%BD%91%E7%BB%9C%E6%80%A7%E8%83%BD',
         '演示带宽、时延与丢包率的测量方法及优化思路。'),
        ('路由协议 RIP 与 OSPF 详解课件', 'ppt', 4, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '对比距离矢量与链路状态算法的收敛过程与适用场景。'),
        ('网络工程认证备考题集', 'question', 5, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '覆盖路由交换、网络安全与网络设计的综合性题目。'),
        ('计算机网络仿真实验指导书', 'doc', 3, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '基于仿真软件搭建网络拓扑并验证协议行为的实验步骤。'),
        ('IPv6 与移动 IP 技术讲座', 'video', 4, 'https://search.bilibili.com/all?keyword=IPv6',
         '讲解地址结构、过渡技术与移动性支持方案。'),
        ('防火墙与入侵检测基础', 'doc', 3, 'https://www.icourse163.org/search.htm?search=%E7%BD%91%E7%BB%9C%E5%AE%89%E5%85%A8',
         '介绍访问控制策略、包过滤技术及常见入侵检测方法。'),
        ('网络协议分析与设计题库', 'question', 4, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '训练协议报文设计与状态机分析能力。'),
        ('网络课程知识点思维导图', 'doc', 1, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C',
         '以思维导图形式串联五层模型全部核心考点，适合考前速览。'),
    ],
    "算法": [
        ('LeetCode 算法题库', 'question', 3, 'https://leetcode.cn/problemset/?search=%E7%AE%97%E6%B3%95',
         '按数据结构与算法标签分类的在线题库，含题解与讨论区。'),
        ('《算法导论》核心章节精讲', 'video', 5, 'https://search.bilibili.com/all?keyword=%E7%AE%97%E6%B3%95%E5%AF%BC%E8%AE%BA',
         '讲解分治、动态规划、贪心与图算法的正确性证明与实现。'),
        ('数据结构与算法（清华邓俊辉）公开课', 'video', 3, 'https://www.xuetangx.com/search?query=%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84',
         '从向量、列表讲到图与搜索树，代码实现与复杂度分析并重。'),
        ('动态规划专题精讲', 'video', 4, 'https://search.bilibili.com/all?keyword=%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92',
         '以 20 道例题覆盖背包、区间、树形与状态压缩等经典模型。'),
        ('排序算法可视化演示', 'ppt', 2, 'https://visualgo.net/zh',
         '交互式动画对比各排序算法的执行过程与时间空间复杂度。'),
        ('LeetCode 高频题解合集', 'doc', 3, 'https://leetcode.cn/problemset/?search=%E7%AE%97%E6%B3%95',
         '汇总面试高频题的多解法思路与复杂度分析。'),
        ('图论算法入门：最短路与最小生成树', 'video', 4, 'https://search.bilibili.com/all?keyword=%E5%9B%BE%E8%AE%BA%E7%AE%97%E6%B3%95',
         '讲解 Dijkstra、Floyd、Kruskal 与 Prim 算法的实现与应用。'),
        ('算法复杂度分析讲义', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E7%AE%97%E6%B3%95%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%88%86%E6%9E%90',
         '讲解渐进记号、递推式求解与均摊分析方法。'),
        ('算法刷题笔记与模板', 'doc', 4, 'https://labuladong.online/',
         '按题型归纳解题框架与可直接复用的代码模板，适合系统训练。'),
        ('贪心算法经典题集', 'question', 3, 'https://leetcode.cn/problemset/?search=%E8%B4%AA%E5%BF%83',
         '覆盖区间调度、跳跃游戏等典型贪心建模题目。'),
        ('KMP 与字符串匹配算法精讲', 'video', 4, 'https://search.bilibili.com/all?keyword=KMP%20%E7%AE%97%E6%B3%95',
         '深入讲解 next 数组推导过程与字符串算法的扩展应用。'),
        ('二叉搜索树与平衡树实验课件', 'ppt', 3, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84',
         '讲解 BST、AVL 与红黑树的旋转及插入删除过程。'),
        ('回溯与剪枝算法专题', 'video', 3, 'https://search.bilibili.com/all?keyword=%E5%9B%9E%E6%BA%AF%E7%AE%97%E6%B3%95',
         '以排列组合、N 皇后为例讲解搜索空间组织与剪枝策略。'),
        ('算法期末复习题库', 'question', 2, 'https://www.icourse163.org/search.htm?search=%E7%AE%97%E6%B3%95%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%88%86%E6%9E%90',
         '覆盖复杂度分析、树、图与排序的经典考题。'),
        ('分治算法与归并排序实战', 'video', 3, 'https://search.bilibili.com/all?keyword=%E5%88%86%E6%B2%BB%E7%AE%97%E6%B3%95',
         '讲解分治三步法及其典型应用，如逆序对统计问题。'),
        ('哈希表原理与冲突解决讲义', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84',
         '讲解散列函数设计、开放定址法与链地址法的实现权衡。'),
        ('蓝桥杯算法竞赛真题集', 'question', 4, 'https://www.lanqiao.cn/problems/?keyword=%E8%93%9D%E6%A1%A5%E6%9D%AF',
         '历年真题与解析，覆盖模拟、搜索与动态规划等题型。'),
        ('位运算技巧题库', 'question', 4, 'https://leetcode.cn/problemset/?search=%E4%BD%8D%E8%BF%90%E7%AE%97',
         '训练位运算在状态压缩与高效判断中的应用技巧。'),
        ('并查集与高级数据结构课件', 'ppt', 4, 'https://www.icourse163.org/search.htm?search=%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84',
         '讲解并查集优化、线段树与树状数组的基础操作。'),
        ('算法设计与分析（北大）公开课', 'video', 4, 'https://www.icourse163.org/search.htm?search=%E7%AE%97%E6%B3%95%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%88%86%E6%9E%90',
         '系统讲解算法设计范式与复杂度下界分析。'),
        ('双指针与滑动窗口题型归纳', 'doc', 3, 'https://leetcode.cn/problemset/?search=%E6%BB%91%E5%8A%A8%E7%AA%97%E5%8F%A3',
         '归纳同向、相向双指针与定长滑窗法的适用特征。'),
        ('网络流算法入门讲义', 'doc', 5, 'https://www.icourse163.org/search.htm?search=%E7%AE%97%E6%B3%95%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%88%86%E6%9E%90',
         '讲解最大流最小割定理与常见的网络流建图方法。'),
        ('算法竞赛入门经典习题解答', 'question', 5, 'https://www.luogu.com.cn/problem/list?keyword=%E7%AE%97%E6%B3%95',
         '配套题单与题解，适合竞赛方向进阶训练。'),
        ('二分查找与答案二分专题', 'video', 3, 'https://search.bilibili.com/all?keyword=%E4%BA%8C%E5%88%86%E6%9F%A5%E6%89%BE',
         '讲解单调性判定方法与二分答案的常见套路。'),
        ('单调栈与单调队列应用课件', 'ppt', 3, 'https://leetcode.cn/problemset/?search=%E5%8D%95%E8%B0%83%E6%A0%88',
         '讲解滑动窗口最值与下一个更大元素等典型应用。'),
        ('算法可视化学习工具集', 'doc', 1, 'https://visualgo.net/',
         '交互式演示常见数据结构与算法的执行过程。'),
    ],
    "Web开发": [
        ('HTML5 与 CSS3 基础教程', 'doc', 1, 'https://www.runoob.com/html/html5-intro.html',
         '从标签语义到选择器与盒模型的基础教程，附在线示例可直接运行。'),
        ('JavaScript 学习指南', 'doc', 3, 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript',
         'MDN 官方文档，覆盖语法、原型链、异步编程与模块化。'),
        ('Vue 3 官方文档与实战', 'doc', 3, 'https://cn.vuejs.org/',
         '讲解响应式原理、组合式 API 与组件通信，含完整示例代码。'),
        ('React 官方入门教程', 'doc', 3, 'https://zh-hans.react.dev/learn',
         '从组件、状态到 Hooks 的渐进式教程，含交互式练习。'),
        ('前端工程化与构建工具', 'video', 4, 'https://search.bilibili.com/all?keyword=%E5%89%8D%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%8C%96',
         '讲解模块化规范、打包原理与 Vite/Webpack 配置实践。'),
        ('CSS 布局实战：Flex 与 Grid', 'video', 2, 'https://search.bilibili.com/all?keyword=CSS%20Flex%20Grid',
         '用真实页面案例讲解两种现代布局方案的用法与选型。'),
        ('浏览器工作原理与性能优化', 'doc', 4, 'https://developer.mozilla.org/zh-CN/docs/Web/Performance',
         '讲解渲染流程、重排重绘与关键渲染路径的优化方法。'),
        ('前端面试题库', 'question', 3, 'https://search.bilibili.com/all?keyword=%E5%89%8D%E7%AB%AF%E9%9D%A2%E8%AF%95',
         '覆盖 HTML/CSS/JS 与网络知识的高频面试题及解析。'),
        ('Node.js 官方入门指南', 'doc', 3, 'https://nodejs.org/zh-cn/learn',
         '介绍事件循环、模块系统与基础服务端编程。'),
        ('Express 与 Koa 接口开发实战', 'video', 4, 'https://search.bilibili.com/all?keyword=Node.js%20Express',
         '从路由、中间件到鉴权，完整实现一套可用的后端接口。'),
        ('前后端分离项目实战：博客系统', 'video', 4, 'https://search.bilibili.com/all?keyword=%E5%89%8D%E5%90%8E%E7%AB%AF%E5%88%86%E7%A6%BB%20%E9%A1%B9%E7%9B%AE',
         '完整走通需求分析、接口设计、前端联调到部署上线的全流程。'),
        ('Web 安全：XSS 与 CSRF 防护', 'doc', 4, 'https://developer.mozilla.org/zh-CN/docs/Web/Security',
         '讲解常见前端攻击原理与防御性编码实践。'),
        ('响应式网页设计课件', 'ppt', 2, 'https://www.icourse163.org/search.htm?search=Web%20%E5%89%8D%E7%AB%AF%E5%BC%80%E5%8F%91',
         '讲解媒体查询、流式布局与移动优先的设计思路。'),
        ('Web 前端课程设计任务书', 'question', 3, 'https://www.icourse163.org/search.htm?search=Web%20%E5%89%8D%E7%AB%AF%E5%BC%80%E5%8F%91',
         '提供选题范围、功能要求与验收标准，可直接使用。'),
        ('TypeScript 从入门到实践', 'doc', 3, 'https://www.typescriptlang.org/docs/',
         '讲解类型系统、泛型与工程配置，附从 JS 迁移的建议。'),
        ('微信小程序开发入门', 'video', 3, 'https://developers.weixin.qq.com/miniprogram/dev/framework/',
         '讲解小程序框架、常用组件与云开发能力。'),
        ('Webpack 打包配置详解', 'doc', 4, 'https://webpack.js.org/concepts/',
         '讲解入口、loader、插件机制与代码分割配置。'),
        ('Ajax 与 Fetch API 使用教程', 'doc', 2, 'https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API',
         '讲解异步请求、跨域处理与失败重试的实践写法。'),
        ('Element Plus 组件库使用手册', 'doc', 2, 'https://element-plus.org/zh-CN/',
         '面向 Vue 3 的组件库文档，含按需引入与主题定制说明。'),
        ('单页应用路由原理与实现', 'video', 4, 'https://search.bilibili.com/all?keyword=%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1',
         '讲解 hash 与 history 两种路由模式、懒加载与路由守卫。'),
        ('浏览器开发者工具入门', 'doc', 2, 'https://developer.mozilla.org/zh-CN/docs/Learn/Common_questions/Tools_and_setup/What_are_browser_developer_tools',
         '介绍浏览器开发者工具的基本面板与常见调试流程。'),
        ('Web 性能优化与测量方法', 'doc', 4, 'https://developer.mozilla.org/zh-CN/docs/Learn/Performance',
         '讲解页面性能的核心指标、测量工具与常见优化手段。'),
        ('HTML/CSS 基础自测题', 'question', 1, 'https://www.runoob.com/quiz/html-quiz.html',
         '在线自测题，适合初学者检验基础知识掌握情况。'),
        ('全栈项目部署与运维入门', 'video', 4, 'https://search.bilibili.com/all?keyword=Nginx%20%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2',
         '讲解服务器环境准备、Nginx 配置与自动化部署流程。'),
        ('RESTful API 设计规范', 'doc', 3, 'https://restfulapi.net/',
         '讲解资源命名、HTTP 状态码使用与接口版本化策略。'),
        ('前端状态管理实践', 'doc', 3, 'https://pinia.vuejs.org/zh/',
         '讲解 Pinia 的 store 设计、跨组件状态共享与持久化。'),
        ('Web 前端实训项目合集', 'question', 3, 'https://www.icourse163.org/search.htm?search=Web%20%E5%89%8D%E7%AB%AF%E5%BC%80%E5%8F%91',
         '收录多个实训题目与功能清单，适合阶段性动手练习。'),
        ('浏览器兼容性处理经验笔记', 'doc', 3, 'https://caniuse.com/',
         '讲解特性查询、前缀处理与兼容方案的选型思路。'),
        ('PWA 渐进式 Web 应用入门', 'doc', 4, 'https://developer.mozilla.org/zh-CN/docs/Web/Progressive_web_apps',
         '讲解 Service Worker、离线缓存与可安装体验的实现。'),
        ('前端代码规范与 ESLint 配置', 'doc', 2, 'https://eslint.org/docs/latest/',
         '讲解规则配置、共享配置包与自动修复的实践。'),
        ('ECharts 数据可视化实战', 'video', 3, 'https://echarts.apache.org/zh/index.html',
         '讲解常用图表配置、数据绑定与多图交互联动。'),
        ('前端课程实验报告范例', 'doc', 2, 'https://www.icourse163.org/search.htm?search=Web%20%E5%89%8D%E7%AB%AF%E5%BC%80%E5%8F%91',
         '提供实验过程记录与结果分析的规范写法示例。'),
        ('TensorFlow.js 前端深度学习应用', 'doc', 5, 'https://tensorflow.google.cn/js',
         '讲解在浏览器中加载模型并完成推理的完整流程。'),
        ('Web 开发综合练习题集', 'question', 2, 'https://www.runoob.com/quiz/javascript-quiz.html',
         '覆盖 HTML/CSS/JavaScript 的综合自测题。'),
    ],
    "人工智能": [
        ('人工智能导论（国家精品课）', 'video', 3, 'https://www.icourse163.org/search.htm?search=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD',
         '系统介绍搜索、推理、学习与智能体等人工智能核心内容。'),
        ('吴恩达深度学习专项课程', 'video', 4, 'https://www.coursera.org/specializations/deep-learning',
         '五门课程组成的深度学习体系，从神经网络基础到序列模型。'),
        ('神经网络与深度学习（邱锡鹏）', 'doc', 4, 'https://nndl.github.io/',
         '开源教材，系统讲解前馈网络、注意力机制与生成模型。'),
        ('计算机视觉入门：CNN 与图像分类', 'video', 4, 'https://search.bilibili.com/all?keyword=%E8%AE%A1%E7%AE%97%E6%9C%BA%E8%A7%86%E8%A7%89',
         '讲解卷积、池化与经典网络结构及训练调优技巧。'),
        ('自然语言处理基础讲义', 'doc', 4, 'https://www.icourse163.org/search.htm?search=%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E5%A4%84%E7%90%86',
         '覆盖分词、词向量表示、序列标注与文本分类任务。'),
        ('强化学习导论（Sutton 教材）', 'doc', 5, 'http://incompleteideas.net/book/the-book-2nd.html',
         '强化学习领域经典教材，含马尔可夫决策过程与值函数近似。'),
        ('人工智能期末复习题库', 'question', 2, 'https://www.icourse163.org/search.htm?search=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD',
         '覆盖搜索算法、知识表示与推理的经典考题。'),
        ('Transformer 与大模型原理详解', 'video', 5, 'https://search.bilibili.com/all?keyword=Transformer',
         '讲解自注意力机制、位置编码与预训练范式的演进脉络。'),
        ('TensorFlow 官方教程', 'doc', 3, 'https://tensorflow.google.cn/tutorials',
         '官方入门与进阶教程，涵盖图像、文本与结构化数据任务（国内可直连）。'),
        ('知识图谱构建与应用案例', 'doc', 4, 'https://www.icourse163.org/search.htm?search=%E7%9F%A5%E8%AF%86%E5%9B%BE%E8%B0%B1',
         '讲解实体抽取、关系抽取与图数据库的应用落地。'),
        ('计算机视觉课程设计任务书', 'question', 4, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E8%A7%86%E8%A7%89',
         '提供图像分类、目标检测等选题与验收标准。'),
        ('人工智能伦理与安全讲座', 'video', 3, 'https://search.bilibili.com/all?keyword=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD%E4%BC%A6%E7%90%86',
         '讨论算法公平性、隐私保护与生成内容治理等议题。'),
        ('语音识别技术入门课件', 'ppt', 4, 'https://www.icourse163.org/search.htm?search=%E8%AF%AD%E9%9F%B3%E8%AF%86%E5%88%AB',
         '讲解声学特征提取、声学模型与语言模型的基本框架。'),
        ('ModelScope 魔搭社区模型使用指南', 'doc', 3, 'https://www.modelscope.cn/',
         '国内模型社区，提供预训练模型的检索、下载、在线体验与微调实践。'),
        ('生成对抗网络（GAN）原理解析', 'video', 5, 'https://search.bilibili.com/all?keyword=GAN%20%E7%94%9F%E6%88%90%E5%AF%B9%E6%8A%97%E7%BD%91%E7%BB%9C',
         '讲解对抗训练机制与常见 GAN 变体的改进思路。'),
        ('人工智能数学基础讲义', 'doc', 3, 'https://www.icourse163.org/search.htm?search=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD',
         '梳理矩阵运算、概率论与优化方法在人工智能中的应用。'),
        ('智能推荐系统算法实践', 'doc', 4, 'https://www.icourse163.org/search.htm?search=%E6%8E%A8%E8%8D%90%E7%B3%BB%E7%BB%9F',
         '讲解协同过滤、矩阵分解与排序模型的工程实现。'),
        ('大模型提示工程实战指南', 'doc', 3, 'https://platform.openai.com/docs/guides/prompt-engineering',
         '讲解提示设计原则、少样本示例与输出约束技巧。'),
        ('计算机视觉期末题库', 'question', 3, 'https://www.icourse163.org/search.htm?search=%E8%AE%A1%E7%AE%97%E6%9C%BA%E8%A7%86%E8%A7%89',
         '覆盖卷积计算、感受野分析与损失函数设计题型。'),
        ('多模态学习与跨模态检索', 'video', 5, 'https://search.bilibili.com/all?keyword=%E5%A4%9A%E6%A8%A1%E6%80%81',
         '讲解图文对齐、对比学习与跨模态检索系统架构。'),
        ('人工智能实验指导书（Python 实现）', 'doc', 3, 'https://www.icourse163.org/search.htm?search=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD',
         '提供搜索算法、聚类与神经网络的实验代码框架。'),
        ('YOLO 系列目标检测算法详解', 'video', 4, 'https://search.bilibili.com/all?keyword=YOLO%20%E7%9B%AE%E6%A0%87%E6%A3%80%E6%B5%8B',
         '讲解单阶段检测思路与各版本的关键改进点。'),
        ('人工智能竞赛实战题集', 'question', 5, 'https://tianchi.aliyun.com/search?keyword=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD',
         '汇总计算机视觉与自然语言处理方向赛题及优秀方案思路。'),
        ('智能问答系统设计与实现课件', 'ppt', 4, 'https://www.icourse163.org/search.htm?search=%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E5%A4%84%E7%90%86',
         '讲解检索式与生成式问答系统的整体架构设计。'),
        ('深度学习模型压缩与部署', 'doc', 4, 'https://pytorch.org/tutorials/',
         '讲解剪枝、量化与推理加速的实践路径。'),
        ('人工智能导论知识点思维导图', 'doc', 1, 'https://www.icourse163.org/search.htm?search=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD',
         '用思维导图串联人工智能主要分支与核心概念。'),
        ('机器人感知与决策入门', 'video', 4, 'https://search.bilibili.com/all?keyword=%E6%9C%BA%E5%99%A8%E4%BA%BA%20%E8%B7%AF%E5%BE%84%E8%A7%84%E5%88%92',
         '讲解多传感器融合、定位与路径规划基础知识。'),
        ('人工智能专业英语术语手册', 'doc', 2, 'https://www.icourse163.org/search.htm?search=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD',
         '汇总常用专业术语的中英对照与简明释义。'),
        ('人工智能课程综合设计题库', 'question', 4, 'https://www.icourse163.org/search.htm?search=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD',
         '提供综合设计题目、实现要求与验收标准。'),
    ],
}

# ---- 类型扩充重分类（模块加载时应用，保证重跑导入不回退）----
# book（书籍/教材）：书名号或"教材"字样；course（系列课程）：成体系的系列课/公开课/合集
# 仅从 doc / video 两类中划出，笔记类仍算文档，课件/题库不动
import re as _re

_BOOK_PAT = _re.compile(r'《[^》]+》|教材|权威指南|动手学深度学习|神经网络与深度学习')
_COURSE_PAT = _re.compile(r'系列|合集|公开课|速成课程|完整课程|系统课程|专项课程|训练营|微专业')


def _retype(title, ty):
    if ty not in ('doc', 'video'):
        return ty
    if ty == 'doc' and _BOOK_PAT.search(title):
        return 'book'                        # 具名书籍/教材的文档配套也算书籍
    if '笔记' in title:                      # 其余笔记仍属文档
        return ty
    if _COURSE_PAT.search(title):
        return 'course'
    return ty


for _cat, _items in RESOURCES.items():
    for _i, (_t, _ty, _d, _u, _desc) in enumerate(_items):
        _items[_i] = (_t, _retype(_t, _ty), _d, _u, _desc)
